[package]
name = "financial_tooling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "financial_tooling"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rust-numpy = "0.1.0"
plotly = "0.8.4"
